### ISSUE TITLE
the store file increase very fast

### ISSUE THREAD

**Issue by qgwwm** [rocketmq/spring-boot-starter-rocketmq#5]
when I started the rocketmq starter the store file increase very fast. and at the same time,I just start an producer sending message at one message per three second.no customer.I find the file rocketme/store/index/***,every file has about 400M.Just a few seconds,the disk full.please help me,thanks.

**Comment by he-jialin2** [comment]
你好，这是消息索引存储过多,其核心产生的点是IndexService#buildIndex类 可自行去看下源码，可以在配置文件重新配置改变储存位置 
##消息索引存储路径
storePathIndex=/usr/local/rocketmq/store/index

**Comment by qgwwm** [comment]
谢谢回复，已经找到原因了。装broker的那台机器的jdk不知道什么时候换成32位的了。换到64位的就好了。谢谢
